### ISSUE TITLE
Compatible with the latest MediaWiki 1.39?

### ISSUE THREAD

**Issue by fr3nch13** [hexmode/PluggableSSO#4]
I was wondering if this plugin is compatible with the latest stable release of MediaWiki 1.39. Do you, or anyone else know? Is this plugin still being maintained?

**Comment by hexmode** [comment]
This didn't really get off the ground.

What is your use case?

**Comment by fr3nch13** [comment]
I’m looking to add Siteminder to an existing install of MediaWiki. I googled ‘mediawiki siteminder’ and your repo was the second that came up after one that seems to have been archived. On May 1, 2023, at 11:54 AM, Mark A. Hershberger ***@***.***> wrote:﻿
This didn't really get off the ground.
What is your use case?

**Comment by hexmode** [comment]
Ah...

If you can bypass the need for siteminder, something like PluggableAuth's SimpleSAMLphp extension would work with providers like PingID directly.

If you must use siteminder, then you should look at <https://www.mediawiki.org/wiki/Extension:Auth_remoteuser>. PluggableSSO originally targeted PluggableAuth, but PluggableAuth is designed so that it would get the first request.

**Comment by fr3nch13** [comment]
Awesome, thanks for the help!On May 1, 2023, at 1:04 PM, Mark A. Hershberger ***@***.***> wrote:﻿
Closed #4 as completed.
